//navigationTypes.ts
export type RootStackParamList = {
    HomeTabs: undefined;
    SignupScreen: undefined;
    TermsAndConditions: undefined;
    PrivacyPolicy: undefined;
    LoginScreen: undefined;
    ForgotPasswordScreen: undefined;
    CarListScreen: { filterType?: string; filterValue?: any; searchQuery?: string; selectedCity?: string } | undefined;
    Profile:undefined;
    SecurityScreen:undefined;
    City:undefined;
    LanguageScreen: undefined;
    BlogScreen: undefined;
    BlogDetailsPage: { blogId?: string; blog?: any } | undefined;
    VideoScreen: undefined;
    VideoDetailsPage: { videoId?: string; blog?: any } | undefined;
    AdvertisingScreen: undefined;
    SupportPage: undefined;
    CallUsScreen: undefined;
    PostCarAd: undefined;
    PostBikeAd: undefined;
    PostBikeAdFeatured: { selectedPackage?: any } | undefined;
    BikePackageSelection: undefined;
    RentServiceAd: { selectedRegistrationCity?: any } | undefined;
    PostAutoPartsAd: undefined;
    ListItforyou: { selectedPackage?: any } | undefined;
    BuyCarForMeScreen: undefined;
    CarInspectionScreen: { selectedPackage?: any } | undefined;
    CarRentalServiceScreen: undefined;
    BuyCarforMe: { preselectedYear?: string; carChoices?: { make: string; model: string; variant?: string }[]; selectedRegistrationCity?: string; selectedLocation?: string } | undefined;
    BuyCarforMeYearScreen: { returnTo?: string } | undefined;
    BuyCarforMeBrandFlowScreen: { year: string; returnTo?: string };
    BuyCarforMeCityScreen: { returnTo?: string } | undefined;
    BuyCarforMeLocationScreen: { returnTo?: string } | undefined;
    FeaturesSelectorScreen: { preselected?: string[]; returnTo?: string } | undefined;
    AreaSelectorScreen: { city: string; returnTo?: string } | undefined;
    CarInspection: { selectedLocation?: any; selectedPackage?: any } | undefined;
    LocationSelectionScreen: { returnTo?: string } | undefined;
    RegistrationCitySelectionScreen: { returnTo?: string } | undefined;
    PostCarAdFeatured: { selectedPackage?: any; serviceName?: string; price?: string } | undefined;
    MyAds: undefined;
    NewCarListScreen: { filterType?: string; filterValue?: any } | undefined;
    FeaturedCarListScreen:undefined;
    ChatDetailScreen: undefined;
    ForYouCarListScreen:undefined;
    CarDetails: undefined;
    MyFavorite:undefined;
    Notifications: undefined;
    PostFreeAd: undefined;
    PostFeaturedAd: undefined;
    ListItForYouScreen:undefined;
    DetailsScreen:undefined;
    NewCarDetailsScreen: undefined;
    Chat: undefined;
    BikeDetailsScreen: undefined;
    AutoPartsListScreen: undefined;
    BikeListScreen: undefined;
    AllOffersScreen: undefined;
    RentalCarListScreen: undefined;
    RentalCarDetailsScreen: undefined;
    SellBikeScreen: undefined;
    SellAutoScreen: undefined;
    PackagesScreen: { screen?: string } | undefined;
    PackageDetail: { packageId: string };
    PackageUsage: { packageId: string; userPackageId: string };
    PaymentMethod: { packageId: string; amount: number } | undefined;
    PaymentSuccess: { packageId: string; amount: number; paymentMethod: string } | undefined;
    NewBikeListScreen: { filterType?: string; filterValue?: any } | undefined;
    NewBikeDetailsScreen: { carDetails: any } | undefined;
    CarComparison: undefined;
    ComparisonResults: { car1: string; car2: string } | undefined;
    AutoPartsDetailsScreen: { part: any } | undefined;
    PakagesScreen: undefined;
    EditAd: { adId: string };
    CarDetail: { carId: string };
    Sell: undefined;
    InspectionReportView: { inspectionId: string };
    UpgradeFreeAdToPremium: { adId: string; adData: any };
    Payment: { adId: string; adType: string; cost: number; isReactivation: boolean; adData: any } | undefined;
    PaymentScreen: { adId: string; adType: string; cost: number; isReactivation: boolean; adData: any } | undefined;
    NewCarDetails: { carDetails: any } | undefined;
    FAQ: undefined;
    Home: undefined;
  };
  
  